import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { useSession, signOut } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { data: session, status } = useSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <header>
            {status === "loading" ? (
              <p>Loading...</p>
            ) : session ? (
              <div>
                <span>Welcome, {session.user?.email}</span>
                <button onClick={() => signOut()}>Logout</button>
              </div>
            ) : (
              <div>
                <a href="/auth/login">Login</a>
                <a href="/auth/register">Register</a>
              </div>
            )}
          </header>
          <main>{children}</main>
        </SessionProvider>
      </body>
    </html>
  );
}
